---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	hunt_intake(hunt_intake)
	hunt_planner(hunt_planner)
	hunt_tool_executor(hunt_tool_executor)
	hunt_correlator(hunt_correlator)
	hunt_hitl_gate(hunt_hitl_gate)
	__end__([<p>__end__</p>]):::last
	__start__ --> hunt_intake;
	hunt_correlator --> hunt_hitl_gate;
	hunt_intake --> hunt_planner;
	hunt_planner --> hunt_tool_executor;
	hunt_tool_executor --> hunt_correlator;
	hunt_hitl_gate --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
